#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

mkdir -p myriadcoin
wget -qO- https://github.com/myriadteam/myriadcoin/releases/download/v0.18.1.0/myriadcoin-0.18.1.0-arm-linux-gnueabihf.tar.gz | tar xzfv - -C myriadcoin --strip-components=1
mkdir myriadcoin-data
sudo ln -s $DIR/conf/myriadcoin.service /etc/systemd/system/myriadcoin.service
sudo systemctl start myriadcoin
sudo systemctl enable myriadcoin
