#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

echo "Installing Myriadcoin Core..."
mkdir -p myriadcoin
mkdir -p myriadcoin-data
wget -qO- https://github.com/myriadteam/myriadcoin/releases/download/v0.18.1.0/myriadcoin-0.18.1.0-x86_64-linux-gnu.tar.gz | tar xzfv - -C myriadcoin --strip-components=1

${DIR}/install-service 10888
${DIR}/install-bashtop
