#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

echo "Installing Myriadcoin Core..."
mkdir -p myriadcoin
mkdir -p myriadcoin-data
wget -qO- https://github.com/myriadteam/myriadcoin/archive/refs/tags/v0.18.1.0.tar.gz | tar xzfv - -C myriadcoin --strip-components=1

cd myriadcoin/depends
make HOST=arm-linux-gnueabihf NO_QT=1
cd ..
./autogen.sh
CONFIG_SITE=$PWD/depends/arm-linux-gnueabihf/share/config.site ./configure --enable-glibc-back-compat --enable-reduce-exports LDFLAGS=-static-libstdc++
make

${DIR}/set-swapsize 2048
${DIR}/install-service 10888
${DIR}/install-bashtop
