#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

echo "Installing Myriadcoin Core..."
cd ${DIR}/..
mkdir -p ${DIR}/../myriadcoin
mkdir -p ${DIR}/../myriadcoin/bin
mkdir -p ${DIR}/../myriadcoin-data
wget -qO- https://github.com/myriadteam/myriadcoin/archive/refs/tags/v0.18.1.0.tar.gz | tar xzfv - -C myriadcoin --strip-components=1

sudo apt-get update
sudo apt-get install -y build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils python3 libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-program-options-dev libboost-test-dev libboost-thread-dev libdb++-dev libminiupnpc-dev libnatpmp-dev

cd ${DIR}/../myriadcoin/depends
make HOST=arm-linux-gnueabihf NO_QT=1 xCPUARCH=armv6l
cd ..
./autogen.sh
CONFIG_SITE=/home/pi/myriadcoin/depends/arm-linux-gnueabihf/share/config.site ./configure --disable-wallet --disable-tests --disable-bench --disable-gui --disable-shared --enable-reduce-exports --with-miniupnpc --enable-upnp-default --with-natpmp --enable-natpmp-default LDFLAGS=-static-libstdc++
make
cd ${DIR}/..

cp myriadcoin/src/myriadcoind myriadcoin/bin/
cp myriadcoin/src/myriadcoin-cli myriadcoin/bin/

${DIR}/set-swapsize 2048
${DIR}/install-service 10888 "-blocksonly -maxmempool=100 -dbcache=20 -maxorphantx=10 -maxsigcachesize=4 -rpcthreads=1"
${DIR}/install-htop
