#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
HOMEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd)"

echo ${DIR}
echo ${HOMEDIR}

echo "Setting port to $1"
mkdir -p ${DIR}/conf/modified/
cp ${DIR}/conf/myriadcoin.service ${DIR}/conf/modified/myriadcoin.service
sed -i "s/_PORT_/$1/g" ${DIR}/conf/modified/myriadcoin.service
sed -i "s/_ARGS_/$2/g" ${DIR}/conf/modified/myriadcoin.service
sed -i "s/_HOMEDIR_/$HOMEDIR/g" ${DIR}/conf/modified/myriadcoin.service

echo "Removing old service if it exists..."
sudo systemctl stop myriadcoin
sudo systemctl disable myriadcoin

sudo systemctl daemon-reload

echo "Adding service..."
sudo systemctl enable ${DIR}/conf/modified/myriadcoin.service
sudo systemctl start myriadcoin
