#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

echo "Removing old service if it exists..."
sudo systemctl stop myriadcoin
sudo systemctl disable myriadcoin
rm /etc/systemd/system/myriadcoin.service

echo "Adding service..."
sudo ln -s ${DIR}/conf/myriadcoin${1}.service /etc/systemd/system/myriadcoin.service
sudo systemctl start myriadcoin
sudo systemctl enable myriadcoin
