#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

apt-get update
apt-get install sense-hat

echo "Removing old service if it exists..."
systemctl stop xmy-sense-hat
systemctl disable xmy-sense-hat

echo "Adding service..."
systemctl enable ${DIR}/extra/xmy-sense-hat.service
systemctl start xmy-sense-hat
